---
- src: https://www.github.com/mrlesmithjr/ansible-nodejs.git
- src: https://www.github.com/mrlesmithjr/ansible-netdata.git
- src: https://github.com/Asamasach/ansible-nginx
- src: https://github.com/Asamasach/ansible-fail2ban
